Repository c1rcle/yellow-notes-backend, pull requests merged in 2020-03, with the labels that each got.

#7 Fixed code style issues
  YellowNotes.Core/Migrations/20200319171536_CreateDatabase.Designer.cs
  YellowNotes.Core/Migrations/20200319171536_CreateDatabase.cs
  YellowNotes.Core/Migrations/DatabaseContextModelSnapshot.cs
  YellowNotes.Core/Models/User.cs
  YellowNotes.Core/Repositories/UserRepository.cs
  YellowNotes.Core/Services/UserService.cs
Labels: prototype, refactorization

#6 Email service feature
  YellowNotes.Api/Startup.cs
  YellowNotes.Api/appsettings.Development.json
  YellowNotes.Core/Email/EmailConfiguration.cs
  YellowNotes.Core/Email/EmailMessage.cs
  YellowNotes.Core/Services/EmailService.cs
  YellowNotes.Core/Services/IEmailService.cs
  YellowNotes.Core/YellowNotes.Core.csproj
Labels: feature, prototype

#12 Azure Key Vault integration
  .gitignore
  .vscode/launch.json
  .vscode/tasks.json
  YellowNotes.Api/Program.cs
  YellowNotes.Api/Startup.cs
  YellowNotes.Api/YellowNotes.Api.csproj
  YellowNotes.Api/appsettings.Development.json
Labels: feature, prototype

#13 Cancellation token addition and .editorconfig changes
  .editorconfig
  YellowNotes.Core/Repositories/IUserRepository.cs
  YellowNotes.Core/Repositories/UserRepository.cs
  YellowNotes.Core/Services/IUserService.cs
  YellowNotes.Core/Services/UserService.cs
Labels: enhancement, prototype

#9 Cors feature
  YellowNotes.Api/Startup.cs
  YellowNotes.Api/appsettings.json
Labels: feature, prototype

#8 Api controller feature
  YellowNotes.Api/Controllers/UserController.cs
  YellowNotes.Api/Filters/ValidateModelStateFilter.cs
  YellowNotes.Api/Properties/launchSettings.json
  YellowNotes.Api/Startup.cs
  YellowNotes.Api/YellowNotes.Api.csproj
  YellowNotes.Api/appsettings.json
  YellowNotes.Core/Services/IUserService.cs
  YellowNotes.Core/Services/UserService.cs
  YellowNotes.Core/Utility/TokenParser.cs
  YellowNotes.Core/YellowNotes.Core.csproj
Labels: feature, prototype

#15 Prepare application for deployment
  .editorconfig
  .github/workflows/deploy.yml
  .gitignore
  .vscode/launch.json
  .vscode/tasks.json
  YellowNotes.Api/Controllers/UserController.cs
  YellowNotes.Api/Filters/ValidateModelStateFilter.cs
  YellowNotes.Api/Program.cs
  YellowNotes.Api/Properties/launchSettings.json
  YellowNotes.Api/Startup.cs
  YellowNotes.Api/YellowNotes.Api.csproj
  YellowNotes.Api/appsettings.json
  YellowNotes.Core/DatabaseContext.cs
  YellowNotes.Core/Dtos/UserDto.cs
  YellowNotes.Core/Email/EmailConfiguration.cs
  YellowNotes.Core/Email/EmailMessage.cs
  YellowNotes.Core/Migrations/20200319171536_CreateDatabase.Designer.cs
  YellowNotes.Core/Migrations/20200319171536_CreateDatabase.cs
  YellowNotes.Core/Migrations/DatabaseContextModelSnapshot.cs
  YellowNotes.Core/Models/User.cs
  YellowNotes.Core/Repositories/IUserRepository.cs
  YellowNotes.Core/Repositories/UserRepository.cs
  YellowNotes.Core/Services/EmailService.cs
  YellowNotes.Core/Services/IEmailService.cs
  YellowNotes.Core/Services/IUserService.cs
  YellowNotes.Core/Services/UserService.cs
  YellowNotes.Core/Utility/EmailGenerator.cs
  YellowNotes.Core/Utility/TokenParser.cs
  YellowNotes.Core/YellowNotes.Core.csproj
Labels: prototype

#17 Apply fixes to the production branch
  YellowNotes.Core/Services/EmailService.cs
Labels: bug

#20 Apply demo improvements to production build
  YellowNotes.Api/Controllers/UserController.cs
  YellowNotes.Api/EmailTemplate.html
  YellowNotes.Api/Startup.cs
  YellowNotes.Api/appsettings.json
  YellowNotes.Core/Email/EmailMessage.cs
  YellowNotes.Core/Services/EmailService.cs
  YellowNotes.Core/Utility/EmailGenerator.cs
Labels: enhancement, prototype
